# Generated by Django 4.0.6 on 2022-07-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comments', models.CharField(max_length=255)),
                ('fact_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(max_length=255)),
                ('like', models.IntegerField(null=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
