# Generated by Django 4.0.6 on 2022-07-12 18:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_comments_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='fact',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
