# Generated by Django 4.0.6 on 2022-07-12 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_fact_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
    ]
